# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matthew Andres Moreno
email: m.more500@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  doctoral student, Michigan State University
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mmore500.github.io" # the base hostname & protocol for your site
twitter_username: morenomatthewa
github_username:  mmore500

plugins_dir:
  - jemoji

# Build settings
markdown: kramdown

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
